development:
  sessions:
    default:
      database: juco-rails
      hosts:
        - localhost:27017

production:
  sessions:
    default:
      database: juco-rails
      hosts:
        - localhost:27017
#      uri: <%= ENV['MONGOLAB_URI'] %>
#      options:
#        safe: true
#        skip_version_check: true